### PR TITLE
feat: final revisions

### PR DESCRIPTION
**Pull request by galvez**

### CODE REVIEW

**Comment by ryansolid** [comment]
If you are going to remove keyed from vue you shouldn't key the rest of them. Key has a specific meaning in any client side framework. To be equivalent to the others it shouldn't be removed.

**Comment by galvez** [comment]
Think this updated piece only goes out tomorrow — feel free to commit improvements to the Solid version as long as it doesn't break the consistency rules. I've added you as a collaborator on my repo.

**Comment by ryansolid** [comment]
It is getting close to the end of my work day so I'm scrambling a bit here. I do have a question though. Why `toFixed`? Like it adds extra overhead on the rendering and it doesn't make the CSS any more accurate. It could be considered busy work I guess but the excess bandwidth over HTML doesn't make up for the computational cost I think. So it's like busy work for no gain. 

Also I don't think template literals as a consistency rule for style is fair. You did it so Vue could be faster, but it makes Solid slower. It's stylistic choice that shouldn't be normalized. I guess the question is what do you want normalized? The output? The input? You can't get normalized output as it is because every framework has their own markers and identifiers. You can't get normalized input because they have different templating/reactivity. As we learned in the JS Framework Benchmark, the only thing you can do is have concrete behavioral constraints and then let every implementation be written in the way most optimal for them. Otherwise its picking favorites. And I won't support that.

**Comment by galvez** [comment]
Without it, there's a rendering mismatch on Vue and React. 

Something about the float precision in Node and on the browser, it seems to vary a lot. 

I think you make a good case re: style attribute being rendered to the best of each framework's idiomatic ability — since React actually requires us to use an object. Feel free to change that in the Solid version as well!

**Comment by galvez** [comment]
You should have gotten an invite to my repo where this PR stems from. Please push directly to my branch.

**Comment by ryansolid** [comment]
Ok. I'm glad I got to review this as the results here changed considerably over something as trivial as adding `toFixed(2)` which you would think would just add a little bit of extra processing to everyone. But it had a different effect. It reduced the overall bandwidth of the HTML document being sent. Significantly enough that the size difference actually makes a bigger impact now on what `autocannon` shows. Remember `autocannon` doesn't just test raw render performance but also how long it takes to transfer all the bytes.

Tools that have larger HTML output to help with hydration got punished more, ie this favors libraries that don't hydrate (fastify-html) or that use Virtual DOMs (Vue, Preact, React) and as to not depend on as many HTML markers. This advantage would disappear as pages got larger but now has more impact on the final results. Given what this benchmark intends to show this is probably fair but I don't really have much to add. Solid has the largest output because of our hydration IDs. This was masked previously by large style elements and is the cause of the drop for us. Even removing our inline script that does event replay and manages streaming, which is included but not being used in this benchmark, showed a 20-30 request improvement. I turned off hydration so that we generated the same HTML output as the others and sure enough we score right near the top (Between fastify-html, and vue).

I don't believe turning off hydration features is in the spirit of this benchmark even if it means that Solid's score is punished by having slightly larger payloads due to the way this benchmark measures speed. I think the message is clear that client frameworks are essentially no slower than specialized HTML renderers especially when you consider what they offer (ie.. interactive client components). And that should come as a surprise to no one considering we've had almost a decade to optimize them for this case.

Go ahead and merge and publish etc... I won't be changing anything else. It looks legit.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
